const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const is_debug = optimize == .Debug;
    const is_linux = target.result.os.tag == .linux;
    const is_macos = target.result.os.tag == .macos;
    const needs_pic = true;

    const h2o_dep = b.dependency("h2o", .{
        .target = target,
        .optimize = optimize,
        .@"use-boringssl" = true,
    });

    const boringssl = b.dependency("boringssl", .{
        .target = target,
        .optimize = optimize,
    });

    const zlib = b.dependency("zlib", .{
        .target = target,
        .optimize = optimize,
        .pie = needs_pic,
    });

    const zstd = b.dependency("zstd", .{
        .target = target,
        .optimize = optimize,
        .pie = needs_pic,
    });

    const brotli = b.dependency("brotli_build", .{
        .target = target,
        .optimize = optimize,
        .pie = needs_pic,
    });

    const shim = b.addLibrary(.{
        .name = "h2oclj",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
        }),
        .linkage = .dynamic,
    });

    // Disable GC to prevent symbol stripping
    shim.link_gc_sections = false;

    const shim_cflags = blk: {
        var flags = std.ArrayList([]const u8).initCapacity(b.allocator, 10) catch unreachable;
        flags.append(b.allocator, "-std=c17") catch unreachable;
        flags.append(b.allocator, "-Wall") catch unreachable;
        flags.append(b.allocator, "-Wextra") catch unreachable;
        flags.append(b.allocator, "-D_POSIX_C_SOURCE=200809L") catch unreachable;
        flags.append(b.allocator, "-DH2O_USE_LIBUV=0") catch unreachable;

        if (is_debug) {
            flags.append(b.allocator, "-DCLJ_DEBUG=1") catch unreachable;
        } else {
            flags.append(b.allocator, "-DCLJ_DEBUG=0") catch unreachable;
        }

        if (is_linux) {
            flags.append(b.allocator, "-D_GNU_SOURCE") catch unreachable;
        } else if (is_macos) {
            flags.append(b.allocator, "-D_DARWIN_C_SOURCE") catch unreachable;
        }

        break :blk flags.toOwnedSlice(b.allocator) catch unreachable;
    };

    shim.addCSourceFile(.{
        .file = b.path("src/main/native/shim.c"),
        .flags = shim_cflags,
    });

    // Add include paths
    shim.addIncludePath(b.path("src/main/native"));

    // Get h2o-evloop artifact and add its include tree
    const h2o_lib = h2o_dep.artifact("h2o-evloop");
    shim.addIncludePath(h2o_lib.getEmittedIncludeTree());

    // Link ALL static libraries into our final shared library
    // This creates one fat libh2oclj.so with all symbols exposed
    shim.linkLibrary(h2o_lib);
    shim.linkLibrary(boringssl.artifact("bcm"));
    shim.linkLibrary(boringssl.artifact("crypto"));
    shim.linkLibrary(boringssl.artifact("ssl"));
    shim.linkLibrary(boringssl.artifact("decrepit"));
    shim.linkLibrary(zlib.artifact("z"));
    shim.linkLibrary(zstd.artifact("zstd"));
    shim.linkLibrary(brotli.artifact("brotli_lib"));

    shim.linkLibC();
    shim.linkSystemLibrary("pthread");
    shim.linkSystemLibrary("dl");
    shim.linkSystemLibrary("m");

    b.installArtifact(shim);

    shim.installHeader(b.path("src/main/native/shim.h"), "shim.h");

    const compile_flags_step = b.step("compile-flags", "Generate compile_flags.txt for LSP");
    const compile_flags_cmd = b.addSystemCommand(&[_][]const u8{
        "sh",
        "-c",
    });

    var compile_flags_script = std.ArrayList(u8).initCapacity(b.allocator, 1024) catch unreachable;
    compile_flags_script.appendSlice(b.allocator, "echo '# Auto-generated by Zig build - do not edit' > compile_flags.txt") catch unreachable;
    for (shim_cflags) |flag| {
        compile_flags_script.appendSlice(b.allocator, " && echo '") catch unreachable;
        compile_flags_script.appendSlice(b.allocator, flag) catch unreachable;
        compile_flags_script.appendSlice(b.allocator, "' >> compile_flags.txt") catch unreachable;
    }
    compile_flags_script.appendSlice(b.allocator, " && echo '-I") catch unreachable;
    const cwd = std.fs.cwd().realpathAlloc(b.allocator, ".") catch unreachable;
    compile_flags_script.appendSlice(b.allocator, cwd) catch unreachable;
    compile_flags_script.appendSlice(b.allocator, "/src/main/native' >> compile_flags.txt") catch unreachable;
    compile_flags_script.appendSlice(b.allocator, " && echo '-I") catch unreachable;
    compile_flags_script.appendSlice(b.allocator, cwd) catch unreachable;
    compile_flags_script.appendSlice(b.allocator, "/../h2o-zig/zig-out/include' >> compile_flags.txt") catch unreachable;

    compile_flags_cmd.addArg(compile_flags_script.items);
    compile_flags_step.dependOn(&compile_flags_cmd.step);
}
