const std = @import("std");

const TargetConfig = struct {
    query: std.Target.Query,
    dir_name: []const u8,
    lib_name: []const u8,
};

pub fn build(b: *std.Build) void {
    const all_targets = b.option(bool, "all-targets", "Build for all supported platforms") orelse true;
    const optimize = b.standardOptimizeOption(.{});
    const native_target = b.standardTargetOptions(.{});

    const all_target_configs = [_]TargetConfig{
        .{
            .query = .{ .cpu_arch = .x86_64, .os_tag = .linux },
            .dir_name = "linux-x86-64",
            .lib_name = "libh2oclj.so",
        },
        // aarch64 linux is temporarily disabled (brotli PIC issue)
        .{
            .query = .{ .cpu_arch = .aarch64, .os_tag = .linux },
            .dir_name = "linux-aarch64",
            .lib_name = "libh2oclj.so",
        },
        .{
            .query = .{ .cpu_arch = .x86_64, .os_tag = .macos },
            .dir_name = "macos-x86-64",
            .lib_name = "libh2oclj.dylib",
        },
        .{
            .query = .{ .cpu_arch = .aarch64, .os_tag = .macos },
            .dir_name = "macos-aarch64",
            .lib_name = "libh2oclj.dylib",
        },
    };

    if (all_targets) {
        const native = native_target.result;
        const native_arch = native.cpu.arch;
        const native_os = native.os.tag;

        for (all_target_configs) |target_config| {
            const is_native = (target_config.query.cpu_arch == native_arch and target_config.query.os_tag == native_os);

            if (is_native) {
                const native_config = TargetConfig{
                    .query = .{ .cpu_model = .baseline },
                    .dir_name = target_config.dir_name,
                    .lib_name = target_config.lib_name,
                };
                buildShimForTarget(b, native_config, optimize);
            } else {
                buildShimForTarget(b, target_config, optimize);
            }
        }
    } else {
        const native = native_target.result;
        const native_arch = native.cpu.arch;
        const native_os = native.os.tag;

        var matched_config: ?TargetConfig = null;
        for (all_target_configs) |target_config| {
            if (target_config.query.cpu_arch == native_arch and target_config.query.os_tag == native_os) {
                matched_config = TargetConfig{
                    .query = .{ .cpu_model = .baseline },
                    .dir_name = target_config.dir_name,
                    .lib_name = target_config.lib_name,
                };
                break;
            }
        }

        const native_config = matched_config orelse {
            @panic("Unsupported native platform - add it to all_target_configs");
        };

        buildShimForTarget(b, native_config, optimize);
    }

    const compile_flags_step = b.step("compile-flags", "Generate compile_flags.txt for LSP");
    const compile_flags_cmd = b.addSystemCommand(&[_][]const u8{ "sh", "-c" });

    const is_debug = optimize == .Debug;
    const native_os = native_target.result.os.tag;
    const is_linux = native_os == .linux;
    const is_macos = native_os == .macos;

    const debug_flag = if (is_debug) "-DCLJ_DEBUG=1" else "-DCLJ_DEBUG=0";
    const os_flag = if (is_linux) "-D_GNU_SOURCE" else if (is_macos) "-D_DARWIN_C_SOURCE" else "";

    const cwd = b.pathFromRoot(".");
    const compile_flags_script = std.fmt.allocPrint(b.allocator,
        \\echo '# Auto-generated by Zig build - do not edit' > ../src/shim/compile_flags.txt && \
        \\echo '-std=c17' >> ../src/shim/compile_flags.txt && \
        \\echo '-Wall' >> ../src/shim/compile_flags.txt && \
        \\echo '-Wextra' >> ../src/shim/compile_flags.txt && \
        \\echo '-Wno-null-pointer-subtraction' >> ../src/shim/compile_flags.txt && \
        \\echo '-Wno-missing-field-initializers' >> ../src/shim/compile_flags.txt && \
        \\echo '-D_POSIX_C_SOURCE=200809L' >> ../src/shim/compile_flags.txt && \
        \\echo '-DH2O_USE_LIBUV=0' >> ../src/shim/compile_flags.txt && \
        \\echo '{s}' >> ../src/shim/compile_flags.txt && \
        \\echo '{s}' >> ../src/shim/compile_flags.txt && \
        \\echo '-I{s}/../src/shim' >> ../src/shim/compile_flags.txt && \
        \\echo '-I{s}/../h2o-zig/zig-out/include' >> ../src/shim/compile_flags.txt
    , .{ debug_flag, os_flag, cwd, cwd }) catch unreachable;

    compile_flags_cmd.addArg(compile_flags_script);
    compile_flags_step.dependOn(&compile_flags_cmd.step);
}

fn buildShimForTarget(b: *std.Build, target_config: TargetConfig, optimize: std.builtin.OptimizeMode) void {
    const target = b.resolveTargetQuery(target_config.query);
    const is_debug = optimize == .Debug;
    const is_linux = target.result.os.tag == .linux;
    const is_macos = target.result.os.tag == .macos;
    const needs_pic = true;

    const h2o_dep = b.dependency("h2o-zig", .{
        .target = target,
        .optimize = optimize,
        .@"use-boringssl" = true,
    });

    const zlib = b.dependency("zlib", .{
        .target = target,
        .optimize = optimize,
        .pie = needs_pic,
    });

    const zstd = b.dependency("zstd", .{
        .target = target,
        .optimize = optimize,
        .pie = needs_pic,
    });

    const brotli = b.dependency("brotli_build", .{
        .target = target,
        .optimize = optimize,
        .pie = needs_pic,
    });

    const artifact_name = std.fmt.allocPrint(
        b.allocator,
        "h2oclj-{s}",
        .{target_config.dir_name},
    ) catch unreachable;

    const shim = b.addLibrary(.{
        .name = artifact_name,
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
        }),
        .linkage = .dynamic,
    });

    shim.link_gc_sections = false;

    const shim_cflags = blk: {
        var flags = std.ArrayList([]const u8).initCapacity(b.allocator, 10) catch unreachable;
        flags.append(b.allocator, "-std=c17") catch unreachable;
        flags.append(b.allocator, "-Wall") catch unreachable;
        flags.append(b.allocator, "-Wextra") catch unreachable;
        flags.append(b.allocator, "-Wno-null-pointer-subtraction") catch unreachable;
        flags.append(b.allocator, "-Wno-missing-field-initializers") catch unreachable;
        flags.append(b.allocator, "-D_POSIX_C_SOURCE=200809L") catch unreachable;
        flags.append(b.allocator, "-DH2O_USE_LIBUV=0") catch unreachable;

        if (is_debug) {
            flags.append(b.allocator, "-DCLJ_DEBUG=1") catch unreachable;
        } else {
            flags.append(b.allocator, "-DCLJ_DEBUG=0") catch unreachable;
        }

        if (is_linux) {
            flags.append(b.allocator, "-D_GNU_SOURCE") catch unreachable;
        } else if (is_macos) {
            flags.append(b.allocator, "-D_DARWIN_C_SOURCE") catch unreachable;
        }

        break :blk flags.toOwnedSlice(b.allocator) catch unreachable;
    };

    shim.root_module.addCSourceFile(.{
        .file = b.path("../src/shim/shim.c"),
        .flags = shim_cflags,
    });

    shim.root_module.addIncludePath(b.path("../src/shim"));

    const h2o_lib = h2o_dep.artifact("h2o-evloop");
    shim.root_module.addIncludePath(h2o_lib.getEmittedIncludeTree());

    if (b.lazyDependency("boringssl", .{
        .target = target,
        .optimize = optimize,
        .pie = needs_pic,
    })) |boringssl| {
        const ssl_artifact = boringssl.artifact("ssl");
        shim.root_module.addIncludePath(ssl_artifact.getEmittedIncludeTree());
    }

    shim.root_module.linkLibrary(h2o_lib);
    shim.root_module.linkLibrary(zlib.artifact("z"));
    shim.root_module.linkLibrary(zstd.artifact("zstd"));
    shim.root_module.linkLibrary(brotli.artifact("brotli_lib"));

    shim.root_module.link_libc = true;
    shim.root_module.linkSystemLibrary("pthread", .{});
    shim.root_module.linkSystemLibrary("dl", .{});
    shim.root_module.linkSystemLibrary("m", .{});

    const install_path = std.fmt.allocPrint(
        b.allocator,
        "{s}/{s}",
        .{ target_config.dir_name, target_config.lib_name },
    ) catch unreachable;

    const install_lib = b.addInstallFileWithDir(
        shim.getEmittedBin(),
        .prefix,
        install_path,
    );
    b.getInstallStep().dependOn(&install_lib.step);

    const mkdir_cmd = b.addSystemCommand(&[_][]const u8{
        "mkdir",
        "-p",
    });
    mkdir_cmd.addArg(std.fmt.allocPrint(
        b.allocator,
        "{s}/resources/{s}",
        .{ target_config.dir_name, target_config.dir_name },
    ) catch unreachable);
    mkdir_cmd.step.dependOn(&install_lib.step);

    const cp_cmd = b.addSystemCommand(&[_][]const u8{
        "cp",
        "-v",
    });
    cp_cmd.addArg(std.fmt.allocPrint(
        b.allocator,
        "zig-out/{s}/{s}",
        .{ target_config.dir_name, target_config.lib_name },
    ) catch unreachable);
    cp_cmd.addArg(std.fmt.allocPrint(
        b.allocator,
        "{s}/resources/{s}/",
        .{ target_config.dir_name, target_config.dir_name },
    ) catch unreachable);
    cp_cmd.step.dependOn(&mkdir_cmd.step);
    b.getInstallStep().dependOn(&cp_cmd.step);

    shim.installHeader(b.path("../src/shim/shim.h"), "shim.h");
}
