# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build and test
        run: nix develop --command bb ci
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # tag: v4.6.2
        with:
          name: platform-shim-jars
          path: |
            shim/linux-*/target/*.jar
            shim/macos-*/target/*.jar
          if-no-files-found: error
          compression-level: 6
